### ISSUE TITLE
USER STORY: As a Site User I can easily register for an account

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#1]
EPIC: Registration and User Accounts

As a **Site User** I can **easily register for an account** so that **I have a personal account and can view my profile**

**Acceptance Criteria**
- [ ] Form has a clear Title "Sign Up"
- [ ] Form has clear instructions on how to sign up, and the benefits of signing up
- [ ] Form has fields such as name, email address, password etc. for quick and easy registration
- [ ] Design of form is consistent with website theme and color

**Tasks**
Task 1: Design, setup and implement django allauth system
Task 2: Customise the signup form and functionality
Task 3: Add form validation messages and handling (e.g. confirmation of registration or incorrectly filled fields)
Task 4: Test registration form functionality 
Task 5: Design submit button and redirect to user-logged homepage
