### ISSUE TITLE
USER STORY: As a Shopper I can sort a specific category of product

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#10]
EPIC:  Sorting and Searching

As a **Shopper** I can **sort a specific category of product** so that **I can find the best-priced and best-rated product in a specific category, or sort the products in that category by name**.

**Acceptance Criteria**
- [ ] Within a category, such as "mobile phones", the user can further categorise by price, rating etc.
- [ ] All products in the selected category should display after the user has clicked
- [ ] All other products will disappear if not in the category selected 

**Tasks**

- [ ] Task 1: Design and implement a dropdown button with further categories such as "rating, price etc"
- [ ] Task 2: Add functionality that removes all items in the unselected categories
- [ ] Task 3: Add functionality that displays all items in the selected categories
- [ ] Task 4: Test category selection functionality
