### ISSUE TITLE
USER STORY: As a Shopper I can sort multiple categories of products simultaneously

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#11]
EPIC: Sorting and Searching

As a **Shopper** I can **sort multiple categories of products simultaneously** so that **I can find the best-priced and best-rated product across broad categories**.

**Acceptance Criteria**
- [ ] User can select more than one category to filter at the same time
- [ ] Both filters will be applied simultaneously
- [ ] Only products in the selected filters will display on the screen to the user

**Tasks**

- [ ] Task 1: Design and implement the filter options, so that the user can select more than one category at the same time
- [ ] Task 2: Ensure functionality of the sorting filter, so that only products that have been selected by the user will display on the screen
- [ ] Task 3: Test sorting filter functionality
