### ISSUE TITLE
USER STORY: As a Shopper I can search for a product by name or description

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#12]
EPIC: Sorting and Searching

As a **Shopper** I can **search for a product by name or description** so that **I can find a specific product I'd like to purchase**.

**Acceptance Criteria**
- [ ] User can easily access the search bar while browsing through the products
- [ ] User can type a keyword in the search bar and the relevant results will appear
- [ ] User can press the search button after typing their search
- [ ] Validation messages will appear if the search is invalid

**Tasks**

- [ ] Task 1: Design and implement search bar which allows users to type in the product they are searching for
- [ ] Task 2: Implement functionality that displays on the products in the searched for category
- [ ] Task 3: Test selected product functionality
- [ ] Task 4: Add validation messages if the user types a product name that does not exist or is invalid
