### ISSUE TITLE
USER STORY: As a Shopper I can view individual product details

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#13]
EPIC: Viewing and Navigation

As a **Shopper** I can **View individual product details** so that **I can select some to purchase and learn more about each product**.

**Acceptance Criteria**
- [ ] Each product has a title, description, category, image and price
- [ ] User are taken to the product details after clicking the button "Read more"
- [ ] User can exit out of the product details and back to the products page by clicking the "Back" button

**Tasks**

- [ ] Task 1: Design and implement the product cards and details
- [ ] Task 2: Add titles, images, descriptions and prices on each product card
- [ ] Task 4: Test product card functionality
- [ ] Task 5: Add link to product card page when user selects the "Back" button
