### ISSUE TITLE
USER STORY: As a Shopper I can easily see what I've searched for and the number of results

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#14]
EPIC: Sorting and Searching

As a **Shopper** I can **easily see what I've searched for and the number of results** so that **I can Quickly decide whether the product I want is available**.

**Acceptance Criteria**
- [ ] User can easily access the search bar while browsing through the products
- [ ] User can type a keyword in the search bar and the relevant results will appear
- [ ] User can press the search button after typing their search
- [ ] Validation messages will appear if the search is invalid

**Tasks**

- [ ] Task 1: Design and implement search bar which allows users to type in the product they are searching for
- [ ] Task 2: Implement functionality that displays on the products in the searched for category
- [ ] Task 3: Test selected product functionality
- [ ] Task 4: Add validation messages if the user types a product name that does not exist or is invalid
