### ISSUE TITLE
USER STORY:As a Shopper I can easily select quantity of a product when purchasing it

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#15]
EPIC: Sorting and Searching

As a **Shopper** I can **easily select quantity of a product when purchasing it** so that **I can ensure I don't accidentally select the wrong product or quantity**.

**Acceptance Criteria**
- [ ] User can easily increase or decrease the number of items of the product by clicking the +/- buttons
- [ ] User can type the quantity in the bar
- [ ] User can use their arrows on the keyboard to adjust the quantity
- [ ] Validation messages will appear if quantity has been added, updated or removed

**Tasks**

- [ ] Task 1: Design and implement +/- buttons and functionality
- [ ] Task 2: Test functionality by changing the quantity of the product
- [ ] Task 3: Implement functionality that displays the new grand total when the quantity is changed
