### ISSUE TITLE
USER STORY: As a Shopper I can view items in my shopping cart to be purchased

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#16]
EPIC: Purchasing and Checkout

As a **Shopper** I can **view items in my bag to be purchased** so that **I can identify the total cost of my purchase and all items I will receive**.

**Acceptance Criteria**
- [ ] User can see the grand total change as they add, remove or update the quantity
- [ ] User can see the product, image, description, quantity and price of their product selections

**Tasks**

- [ ] Task 1: Add functionality to calculate the total price depending on the product and quantity
- [ ] Task 2: Test functionality by changing the quantity of the product
