### ISSUE TITLE
USER STORY: As a Shopper I can adjust the quantity of individual items in my shopping cart

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#17]
EPIC: Purchasing and Checkout

As a **Shopper** I can **adjust the quantity of individual items in my shopping cart** so that **I can easily make changes to my purchase before checkout**.

**Acceptance Criteria**
- [ ] User can easily increase or decrease the number of items of the product in the shopping cart
- [ ] User can type the quantity in the bar (in the shopping cart)
- [ ] User can use their arrows on the keyboard to adjust the quantity (in the shopping cart)
- [ ] Validation messages will appear if quantity has been added, updated or removed (in the shopping cart)

**Tasks**

- [ ] Task 1: Apply +/- buttons and functionality to the shopping cart
- [ ] Task 2: Test functionality by changing the quantity of the product (in the shopping cart)
- [ ] Task 3: Implement functionality that displays the new grand total when the quantity is changed (in the shopping cart)
