### ISSUE TITLE
USER STORY: As a registered shopper I can easily enter my payment information

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#18]
EPIC: Purchasing and Checkout

As a **Registered Shopper** I can **easily enter my payment information** so that **I can Check out quickly and with no hassles**.

**Acceptance Criteria**
- [ ] User can easily increase or decrease the number of items of the product in the shopping cart
- [ ] User can type type their details and will need to fill all required fields
- [ ] User gets a validation message when they do not fill in a field correctly or leave it blank

**Tasks**

- [ ] Task 1: Add stripe form and functionality
- [ ] Task 2: Test functionality by using stripe card
- [ ] Task 3: Test authentication with 3D secure
