### ISSUE TITLE
USER STORY: As a Registered Shopper I can feel my personal and payment information is safe and secure

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#19]
EPIC: Purchasing and Checkout

As a **Registered Shopper** I can **feel my personal and payment information is safe and secure** so that **I can confidently provide the needed information to make a purchase**.

**Acceptance Criteria**
- [ ] User payment goes through 3D authentication system
- [ ] User receives validation messages when they type in a wrong card number
- [ ] User gets confirmation of their purchase and a receipt on their profile page and email

**Tasks**

- [ ] Task 1: Implement Stripe which is a secure payment platform
- [ ] Task 2: Test functionality by using Stripes different cards
- [ ] Task 3: Test validation messages when errors occur
