### ISSUE TITLE
USER STORY: As a Site User I can easily login and logout

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#2]
EPIC: Registration and User Accounts

As a **Site User** I can **login and logout of the site** so that **I can access my personal information**

**Acceptance Criteria**
- [ ] Login/Logout buttons are clear and easy to find
- [ ] Login form has a clear Title "Login"
- [ ] Form has clear instructions on how to login
- [ ] Form has fields of username/email and password etc. for quick and easy login
- [ ] User is redirected to the home page after successfully logging in
- [ ] Design of form is consistent with website theme and color

**Tasks**

- [ ] Task 1: Design, setup and implement django allauth system
- [ ] Task 2: Customise the login/logout form and functionality
- [ ] Task 3: Add form validation messages and handling (e.g. successful login messages or incorrectly filled fields)
- [ ] Task 4: Test login form functionality 
- [ ] Task 5: Design login button and redirect to user-logged in homepage
