### ISSUE TITLE
USER STORY: As a registered shopper I can view an order confirmation after checkout

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#20]
EPIC: Purchasing and Checkout

As a **Registered Shopper** I can **view an order confirmation after checkout** so that **I can verify that I haven't made any mistakes**.

**Acceptance Criteria**
- [ ] User can easily see a table of their order summary on the checkout success page 
- [ ] User can see their order history on their profile page

**Tasks**

- [ ] Task 1: Add and design an order summary table to both the profile page and the checkout success page
- [ ] Task 2: Test functionality by placing orders
