### ISSUE TITLE
USER STORY: As a Registered Shopper I can receive an email confirmation after checking out

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#21]
EPIC: Purchasing and Checkout

As a **Shopper** I can **receive an email confirmation after checking out** so that **I can keep the confirmation of what I've purchased for my records**.

**Acceptance Criteria**
- [ ] User receives an email with confirmation of their order

**Tasks**

- [ ] Task 1: Add email registration using mailchimp
- [ ] Task 2: Test functionality by registering an email address
