### ISSUE TITLE
USER STORY: As a Shopper I can see other shopper's reviews

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#25]
EPIC: Reviewing Products

As a **Shopper** I can **see other shopper's reviews** so that **see what other people think of the product before using it**.

**Acceptance Criteria**
- [ ] User can see reviews when they go onto product details page
- [ ] User cannot add or edit a review until they are logged in as a registered user

**Tasks**

- [ ] Task 1: Add a reviews summary template to the product details section
- [ ] Task 2: Test functionality by adding reviews and logging in as a user
