### ISSUE TITLE
USER STORY: As a Store Owner I can add a FAQ

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#26]
EPIC: Admin and Store Management

As a **Store Owner** I can **add a FAQ** so that **I can add relevant questions for users about my products**.

**Acceptance Criteria**
- [ ] Admin can easily create a new FAQ by filling in the question and answer form
- [ ] Users cannot create a FAQ, but can only view them

**Tasks**

- [ ] Task 1: Design an implement a new FAQ model, view and template to render FAQs
- [ ] Task 2: Test functionality by creating new FAQs
- [ ] Task 3: Test that users who are not admin are given a message saying they can't create or update FAQs
