### ISSUE TITLE
USER STORY: <TITLE>

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#27]
EPIC: Admin and Store Management

As a **Store Owner** I can **update a FAQ** so that **I can update with relevant questions for users about my products**.

**Acceptance Criteria**
- [ ] Admin can easily update a new FAQ by filling in the question and answer form
- [ ] Users cannot update a FAQ, but can only view them

**Tasks**

- [ ] Task 1: Design an implement an update FAQ template that pre-fills the form
- [ ] Task 2: Test functionality by updating new FAQs
- [ ] Task 3: Test that users who are not admin are given a message saying they can't create or update FAQs
