### ISSUE TITLE
USER STORY: <TITLE>

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#28]
EPIC: Admin and Store Management

As a **Store Owner** I can **delete a FAQ** so that **I can delete irrelevant questions for users about my products**.

**Acceptance Criteria**
- [ ] Admin can easily delete a new FAQ by clicking the delete button
- [ ] Users cannot delete a FAQ, but can only view them

**Tasks**

- [ ] Task 1: Add delete button with defensive modal to prevent accidental deletion
- [ ] Task 2: Test functionality by deleting new FAQs
- [ ] Task 3: Test that users who are not admin are given a message saying they can't delete FAQs
