### ISSUE TITLE
USER STORY: As a **Store Owner** I can **add a product**

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#29]
EPIC: Admin and Store Management

As a **Store Owner** I can **add a product** so that **I can add new items to my store**.

**Acceptance Criteria**
- [ ] Admin can easily add a new product by filling in the form
- [ ] Users cannot create a product, but can only view them
- [ ] No Image display will show if product image is not added

**Tasks**

- [ ] Task 1: Design an implement a new Create Product view and template to render products
- [ ] Task 2: Test functionality by creating new Products as admin
- [ ] Task 3: Test that users who are not admin are given a message saying they can't create or update Products
