### ISSUE TITLE
USER STORY: As a Site User I can easily recover my password incase I forget it

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#3]
EPIC: <epic>

As a **Site User** I can **easily recover my password incase I forget it** so that I can **recover access to my account**

**Acceptance Criteria**
- [ ] Forgot my password link is clear and easy to find
- [ ] Clear instructions on how to recover password
- [ ] User is able to verify themselves easily through different methods
- [ ] Email sent to user with new password
- [ ] User can successfully login with new or recovered password

**Tasks**

- [ ] Task 1: Design, setup and implement django allauth system
- [ ] Task 2: Customise the forgot password verification form and functionality
- [ ] Task 3: Add form validation messages and handling (e.g. successful login messages or incorrectly filled fields)
- [ ] Task 4: Ensure user is successfully signed in
