### ISSUE TITLE
USER STORY: As a Store Owner I can delete a product

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#31]
EPIC: Admin and Store Management

As a **Store Owner** I can **delete a product** so that **I can remove old items from my store**.

**Acceptance Criteria**
- [ ] Admin can easily delete a new product by clicking the delete button
- [ ] Defensive programming so products are not deleted by mistake
- [ ] Users cannot delete a product, but can only view them
- [ ] No Image display will show if product image is not added

**Tasks**

- [ ] Task 1: Design an implement a new Remove Product view to remove products
- [ ] Task 2: Test functionality by deleting new Products as admin
- [ ] Task 3: Test that users who are not admin are given a message saying they can't delete Products
