### ISSUE TITLE
USER STORY: As a Site User I can receive an email confirmation after registration

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#4]
EPIC: Registration and User Accounts

As a **Site User** I can **recieve an email confirmation after registration** so that **I can verify that my account registration was successful**

**Acceptance Criteria**
- [ ] Email confirmation is sent to the user after registration

**Tasks**

- [ ] Task 1: Design, setup and implement django allauth system for email confirmation
- [ ] Task 2: Customise email confirmation and functionality
