### ISSUE TITLE
USER STORY: As a Site User I can have a personalised user profile

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#5]
EPIC: Registration and User Accounts

As a **Site User** I can **have a personalised user profile** so that **I can view my personal order history and order confirmations, and save payment information**

**Acceptance Criteria**
- [ ] User has access to their profile immediately after registration
- [ ] User can edit their profile information at anytime
- [ ] User can change their password at anytime
- [ ] User Profile is updated everytime the user adds new information, such as orders or payment methods

**Tasks**

- [ ] Task 1: Design, setup and implement a user profile template
- [ ] Task 2: Customise the profile page and functionality
- [ ] Task 3: Add buttons that allow the user to create, read, edit or delete fields
- [ ] Task 4: Test profile functionality 
- [ ] Task 5: Ensure order history, confirmations and payment information is clear and easy to find
