### ISSUE TITLE
USER STORY: As a shopper I can view a list of products

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#6]
EPIC: Viewing and Navigation

As a **Shopper** I can **view a list of products** so that **I can select some to purchase**

**Acceptance Criteria**
- [ ] Products are listed as cards, all with the same consistency and design
- [ ] Each product has a title, description, category, image and price
- [ ] User can scroll and view all of the products on the page
- [ ] User can select any product to purchase and be redirected to the product details page

**Tasks**

- [ ] Task 1: Design and implement the product cards and details
- [ ] Task 2: Design and display the cards neatly and side by side for the user to compare
- [ ] Task 3: Add titles, images, descriptions and prices on each product card
- [ ] Task 4: Test product card functionality
- [ ] Task 5: Add link to product details page when user selects a product card
