### ISSUE TITLE
USER STORY: As a Shopper I can quickly identify deals, clearance items and special offers

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#7]
EPIC: Viewing and Navigation

As a **Shopper** I can **quickly identify deals, clearance items and special offers** so that **I can select some to purchase**

**Acceptance Criteria**
- [ ] Specials and deals are advertised on the home page
- [ ] There is a tab on the navbar for Specials that navigate the user to the product specials
- [ ] User can select the special and will be redirected to the product details page

**Tasks**

- [ ] Task 1: Design and implement the Home Page to display special offers
- [ ] Task 2: Ensure that the original price is ruled out and displayed next to the special price
- [ ] Task 3: Ensure that the correct special price reflects in the shopping cart when the user clicks a product with a special price
- [ ] Task 4: Test special offer functionality
