### ISSUE TITLE
USER STORY: As a Shopper I can easily view the total of my purchases at any time

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#8]
EPIC: Viewing and Navigation

As a **Shopper** I can **easily view the total of my purchases at any time** so that **I can keep track of how much I am spending**.

**Acceptance Criteria**
- [ ] User can view the total of their purchases on the shopping bag icon, or if they directly click the shopping cart
- [ ] The total will adjust depending on which products the user selects 
- [ ] User can update the total at anytime

**Tasks**

- [ ] Task 1: Design and implement functionality that calculates the total of the user's order
- [ ] Task 2: Ensure the total is displayed to the user at all times
- [ ] Task 3: Add buttons that allow the user easily navigate back to the shopping cart if they choose to add or remove some items
