### ISSUE TITLE
USER STORY: As a Shopper I can sort the list of available products

### ISSUE THREAD

**Issue by pecheylauren02** [pecheylauren02/mp5_posh_portables#9]
EPIC: Sorting and Searching

As a **Shopper** I can **sort the list of available products** so that **I can easily identify the best rated, best priced and categorically sorted products**.

**Acceptance Criteria**
- [ ] User can select a category from a dropdown menu in the navbar to browse on a particular category of products
- [ ] All other unselected products will no longer be displayed after the user selects a category
- [ ] Categories can be by product type or price

**Tasks**

- [ ] Task 1: Design and implement a dropdown button in the navbar so users can select a category to filter out the products they are searching for
- [ ] Task 2: Implement functionality that displays on the products in the selected category
- [ ] Task 3: Test selected product functionality
